// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
insert into expenses (month_id, grp, name, amount, minimum, custom, position)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  (select coalesce(max(position) + 1, 0) from expenses where month_id = $1)
)
returning id, month_id, grp, name, amount, minimum, custom, status, position, created_at
`

type CreateExpenseParams struct {
	MonthID uuid.UUID
	Grp     string
	Name    string
	Amount  int64
	Minimum int64
	Custom  int64
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.MonthID,
		arg.Grp,
		arg.Name,
		arg.Amount,
		arg.Minimum,
		arg.Custom,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Grp,
		&i.Name,
		&i.Amount,
		&i.Minimum,
		&i.Custom,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
delete from expenses where id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpense = `-- name: GetExpense :one
select id, month_id, grp, name, amount, minimum, custom, status, position, created_at from expenses where id = $1
`

func (q *Queries) GetExpense(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Grp,
		&i.Name,
		&i.Amount,
		&i.Minimum,
		&i.Custom,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listExpensesByMonth = `-- name: ListExpensesByMonth :many
select id, month_id, grp, name, amount, minimum, custom, status, position, created_at from expenses
where month_id = $1
order by position, created_at, id
`

func (q *Queries) ListExpensesByMonth(ctx context.Context, monthID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByMonth, monthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.MonthID,
			&i.Grp,
			&i.Name,
			&i.Amount,
			&i.Minimum,
			&i.Custom,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
update expenses set
  grp      = coalesce($1, grp),
  name     = coalesce($2, name),
  amount   = coalesce($3, amount),
  minimum  = coalesce($4, minimum),
  custom   = coalesce($5, custom),
  status   = coalesce($6, status),
  position = coalesce($7, position)
where id = $8
returning id, month_id, grp, name, amount, minimum, custom, status, position, created_at
`

type UpdateExpenseParams struct {
	Grp      pgtype.Text
	Name     pgtype.Text
	Amount   pgtype.Int8
	Minimum  pgtype.Int8
	Custom   pgtype.Int8
	Status   NullExpenseStatus
	Position pgtype.Int4
	ID       uuid.UUID
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.Grp,
		arg.Name,
		arg.Amount,
		arg.Minimum,
		arg.Custom,
		arg.Status,
		arg.Position,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Grp,
		&i.Name,
		&i.Amount,
		&i.Minimum,
		&i.Custom,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
