// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incomes.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIncome = `-- name: CreateIncome :one
insert into incomes (month_id, name, amount, position)
values (
  $1,
  $2,
  $3,
  (select coalesce(max(position) + 1, 0) from incomes where month_id = $1)
)
returning id, month_id, name, amount, status, position, created_at
`

type CreateIncomeParams struct {
	MonthID uuid.UUID
	Name    string
	Amount  int64
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome, arg.MonthID, arg.Name, arg.Amount)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Amount,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
delete from incomes where id = $1
`

func (q *Queries) DeleteIncome(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncome, id)
	return err
}

const getIncome = `-- name: GetIncome :one
select id, month_id, name, amount, status, position, created_at from incomes where id = $1
`

func (q *Queries) GetIncome(ctx context.Context, id uuid.UUID) (Income, error) {
	row := q.db.QueryRow(ctx, getIncome, id)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Amount,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listIncomesByMonth = `-- name: ListIncomesByMonth :many
select id, month_id, name, amount, status, position, created_at from incomes
where month_id = $1
order by position, created_at, id
`

func (q *Queries) ListIncomesByMonth(ctx context.Context, monthID uuid.UUID) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomesByMonth, monthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.MonthID,
			&i.Name,
			&i.Amount,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncome = `-- name: UpdateIncome :one
update incomes set
  name     = coalesce($1, name),
  amount   = coalesce($2, amount),
  status   = coalesce($3, status),
  position = coalesce($4, position)
where id = $5
returning id, month_id, name, amount, status, position, created_at
`

type UpdateIncomeParams struct {
	Name     pgtype.Text
	Amount   pgtype.Int8
	Status   NullIncomeStatus
	Position pgtype.Int4
	ID       uuid.UUID
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.Name,
		arg.Amount,
		arg.Status,
		arg.Position,
		arg.ID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Amount,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
