// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
insert into ledger_entries (person_id, label, amount, source_expense_id)
values (
  $1,
  $2,
  $3,
  $4
)
returning id, person_id, label, amount, source_expense_id, created_at
`

type CreateEntryParams struct {
	PersonID        uuid.UUID
	Label           string
	Amount          int64
	SourceExpenseID *uuid.UUID
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.PersonID,
		arg.Label,
		arg.Amount,
		arg.SourceExpenseID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Label,
		&i.Amount,
		&i.SourceExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
delete from ledger_entries where id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
select id, person_id, label, amount, source_expense_id, created_at from ledger_entries where id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id uuid.UUID) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Label,
		&i.Amount,
		&i.SourceExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonMonthID = `-- name: GetPersonMonthID :one
select month_id from people where id = $1
`

func (q *Queries) GetPersonMonthID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPersonMonthID, id)
	var month_id uuid.UUID
	err := row.Scan(&month_id)
	return month_id, err
}

const listEntriesByMonth = `-- name: ListEntriesByMonth :many
select e.id, e.person_id, e.label, e.amount, e.source_expense_id, e.created_at
from ledger_entries e
join people p on p.id = e.person_id
where p.month_id = $1
order by e.person_id, e.created_at, e.id
`

func (q *Queries) ListEntriesByMonth(ctx context.Context, monthID uuid.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByMonth, monthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Label,
			&i.Amount,
			&i.SourceExpenseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByPerson = `-- name: ListEntriesByPerson :many
select id, person_id, label, amount, source_expense_id, created_at from ledger_entries
where person_id = $1
order by created_at, id
`

func (q *Queries) ListEntriesByPerson(ctx context.Context, personID uuid.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Label,
			&i.Amount,
			&i.SourceExpenseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
update ledger_entries set
  label  = coalesce($1, label),
  amount = coalesce($2, amount)
where id = $3
returning id, person_id, label, amount, source_expense_id, created_at
`

type UpdateEntryParams struct {
	Label  pgtype.Text
	Amount pgtype.Int8
	ID     uuid.UUID
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry, arg.Label, arg.Amount, arg.ID)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Label,
		&i.Amount,
		&i.SourceExpenseID,
		&i.CreatedAt,
	)
	return i, err
}
