// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExpenseStatus string

const (
	ExpenseStatusPending ExpenseStatus = "pending"
	ExpenseStatusPaid    ExpenseStatus = "paid"
)

func (e *ExpenseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseStatus(s)
	case string:
		*e = ExpenseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseStatus: %T", src)
	}
	return nil
}

type NullExpenseStatus struct {
	ExpenseStatus ExpenseStatus
	Valid         bool // Valid is true if ExpenseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseStatus), nil
}

type IncomeStatus string

const (
	IncomeStatusPending  IncomeStatus = "pending"
	IncomeStatusReceived IncomeStatus = "received"
)

func (e *IncomeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncomeStatus(s)
	case string:
		*e = IncomeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncomeStatus: %T", src)
	}
	return nil
}

type NullIncomeStatus struct {
	IncomeStatus IncomeStatus
	Valid        bool // Valid is true if IncomeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncomeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncomeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncomeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncomeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncomeStatus), nil
}

type PersonStatus string

const (
	PersonStatusPending PersonStatus = "pending"
	PersonStatusSettled PersonStatus = "settled"
)

func (e *PersonStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonStatus(s)
	case string:
		*e = PersonStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonStatus: %T", src)
	}
	return nil
}

type NullPersonStatus struct {
	PersonStatus PersonStatus
	Valid        bool // Valid is true if PersonStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PersonStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonStatus), nil
}

type Expense struct {
	ID        uuid.UUID
	MonthID   uuid.UUID
	Grp       string
	Name      string
	Amount    int64
	Minimum   int64
	Custom    int64
	Status    ExpenseStatus
	Position  int32
	CreatedAt time.Time
}

type Income struct {
	ID        uuid.UUID
	MonthID   uuid.UUID
	Name      string
	Amount    int64
	Status    IncomeStatus
	Position  int32
	CreatedAt time.Time
}

type LedgerEntry struct {
	ID              uuid.UUID
	PersonID        uuid.UUID
	Label           string
	Amount          int64
	SourceExpenseID *uuid.UUID
	CreatedAt       time.Time
}

type Month struct {
	ID        uuid.UUID
	UserID    *uuid.UUID
	Label     string
	CreatedAt time.Time
}

type Person struct {
	ID        uuid.UUID
	MonthID   uuid.UUID
	Name      string
	Status    PersonStatus
	Position  int32
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     pgtype.Text
	CreatedAt time.Time
}
