// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: months.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cloneExpenses = `-- name: CloneExpenses :exec
insert into expenses (month_id, grp, name, amount, minimum, custom, status, position)
select $1::uuid, grp, name, amount, minimum, custom, 'pending', position
from expenses
where month_id = $2::uuid
  and id = any($3::uuid[])
`

type CloneExpensesParams struct {
	NewMonthID    uuid.UUID
	SourceMonthID uuid.UUID
	Ids           []uuid.UUID
}

func (q *Queries) CloneExpenses(ctx context.Context, arg CloneExpensesParams) error {
	_, err := q.db.Exec(ctx, cloneExpenses, arg.NewMonthID, arg.SourceMonthID, arg.Ids)
	return err
}

const cloneIncomes = `-- name: CloneIncomes :exec
insert into incomes (month_id, name, amount, status, position)
select $1::uuid, name, amount, 'pending', position
from incomes
where month_id = $2::uuid
  and id = any($3::uuid[])
`

type CloneIncomesParams struct {
	NewMonthID    uuid.UUID
	SourceMonthID uuid.UUID
	Ids           []uuid.UUID
}

func (q *Queries) CloneIncomes(ctx context.Context, arg CloneIncomesParams) error {
	_, err := q.db.Exec(ctx, cloneIncomes, arg.NewMonthID, arg.SourceMonthID, arg.Ids)
	return err
}

const createMonth = `-- name: CreateMonth :one
insert into months (label) values ($1)
returning id, user_id, label, created_at
`

func (q *Queries) CreateMonth(ctx context.Context, label string) (Month, error) {
	row := q.db.QueryRow(ctx, createMonth, label)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonth = `-- name: DeleteMonth :exec
delete from months where id = $1
`

func (q *Queries) DeleteMonth(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonth, id)
	return err
}

const getMonth = `-- name: GetMonth :one
select id, user_id, label, created_at from months where id = $1
`

func (q *Queries) GetMonth(ctx context.Context, id uuid.UUID) (Month, error) {
	row := q.db.QueryRow(ctx, getMonth, id)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listMonths = `-- name: ListMonths :many
select id, label, created_at
from months
order by created_at desc, id desc
`

type ListMonthsRow struct {
	ID        uuid.UUID
	Label     string
	CreatedAt time.Time
}

func (q *Queries) ListMonths(ctx context.Context) ([]ListMonthsRow, error) {
	rows, err := q.db.Query(ctx, listMonths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthsRow{}
	for rows.Next() {
		var i ListMonthsRow
		if err := rows.Scan(&i.ID, &i.Label, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
