// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
insert into people (month_id, name, position)
values (
  $1,
  $2,
  (select coalesce(max(position) + 1, 0) from people where month_id = $1)
)
returning id, month_id, name, status, position, created_at
`

type CreatePersonParams struct {
	MonthID uuid.UUID
	Name    string
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.MonthID, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
delete from people where id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const findPersonByNameInMonth = `-- name: FindPersonByNameInMonth :one
select id, month_id, name, status, position, created_at from people
where month_id = $1 and name = $2
order by position, created_at, id
limit 1
`

type FindPersonByNameInMonthParams struct {
	MonthID uuid.UUID
	Name    string
}

func (q *Queries) FindPersonByNameInMonth(ctx context.Context, arg FindPersonByNameInMonthParams) (Person, error) {
	row := q.db.QueryRow(ctx, findPersonByNameInMonth, arg.MonthID, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
select id, month_id, name, status, position, created_at from people where id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listPeopleByMonth = `-- name: ListPeopleByMonth :many
select id, month_id, name, status, position, created_at from people
where month_id = $1
order by position, created_at, id
`

func (q *Queries) ListPeopleByMonth(ctx context.Context, monthID uuid.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPeopleByMonth, monthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.MonthID,
			&i.Name,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
update people set
  name     = coalesce($1, name),
  status   = coalesce($2, status),
  position = coalesce($3, position)
where id = $4
returning id, month_id, name, status, position, created_at
`

type UpdatePersonParams struct {
	Name     pgtype.Text
	Status   NullPersonStatus
	Position pgtype.Int4
	ID       uuid.UUID
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.Name,
		arg.Status,
		arg.Position,
		arg.ID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.MonthID,
		&i.Name,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
