// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloneExpenses(ctx context.Context, arg CloneExpensesParams) error
	CloneIncomes(ctx context.Context, arg CloneIncomesParams) error
	CreateEntry(ctx context.Context, arg CreateEntryParams) (LedgerEntry, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateMonth(ctx context.Context, label string) (Month, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	DeleteEntry(ctx context.Context, id uuid.UUID) error
	DeleteExpense(ctx context.Context, id uuid.UUID) error
	DeleteIncome(ctx context.Context, id uuid.UUID) error
	DeleteMonth(ctx context.Context, id uuid.UUID) error
	DeletePerson(ctx context.Context, id uuid.UUID) error
	FindPersonByNameInMonth(ctx context.Context, arg FindPersonByNameInMonthParams) (Person, error)
	GetEntry(ctx context.Context, id uuid.UUID) (LedgerEntry, error)
	GetExpense(ctx context.Context, id uuid.UUID) (Expense, error)
	GetIncome(ctx context.Context, id uuid.UUID) (Income, error)
	GetMonth(ctx context.Context, id uuid.UUID) (Month, error)
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	GetPersonMonthID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ListEntriesByMonth(ctx context.Context, monthID uuid.UUID) ([]LedgerEntry, error)
	ListEntriesByPerson(ctx context.Context, personID uuid.UUID) ([]LedgerEntry, error)
	ListExpensesByMonth(ctx context.Context, monthID uuid.UUID) ([]Expense, error)
	ListIncomesByMonth(ctx context.Context, monthID uuid.UUID) ([]Income, error)
	ListMonths(ctx context.Context) ([]ListMonthsRow, error)
	ListPeopleByMonth(ctx context.Context, monthID uuid.UUID) ([]Person, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (LedgerEntry, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
}

var _ Querier = (*Queries)(nil)
